# Generated by Django 2.1.7 on 2019-03-17 22:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophy_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytheresaitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mytheresaitem',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='mytheresaitem',
            name='size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
    ]
